import { RoomConfig } from '../../types'
import { ROOM_COLORS } from '../../constants'

export const ROOMS: RoomConfig[] = [
  // === Top row ===
  {
    id: 'planogram',
    name: 'Planogram Dept',
    x: 0,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.planogram,
    furniture: [
      { type: 'desk', x: 4, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 5, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 4, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 5, y: 10, width: 1, height: 1 },
      { type: 'desk', x: 4, y: 15, width: 3, height: 2 },
      { type: 'monitor', x: 5, y: 15, width: 1, height: 1 },
      { type: 'desk', x: 15, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 16, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 15, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 16, y: 10, width: 1, height: 1 },
      { type: 'desk', x: 15, y: 15, width: 3, height: 2 },
      { type: 'monitor', x: 16, y: 15, width: 1, height: 1 },
      { type: 'plant', x: 2, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 27, y: 2, width: 1, height: 1 },
    ],
    deskPositions: [
      { x: 5, y: 7 },
      { x: 5, y: 12 },
      { x: 5, y: 17 },
      { x: 16, y: 7 },
      { x: 16, y: 12 },
      { x: 16, y: 17 },
    ],
  },
  {
    id: 'hallway',
    name: 'Main Hallway',
    x: 30,
    y: 0,
    width: 10,
    height: 45,
    type: 'hallway',
    color: ROOM_COLORS.hallway,
    furniture: [
      { type: 'plant', x: 32, y: 3, width: 1, height: 1 },
      { type: 'plant', x: 37, y: 3, width: 1, height: 1 },
      { type: 'plant', x: 32, y: 22, width: 1, height: 1 },
      { type: 'plant', x: 37, y: 22, width: 1, height: 1 },
    ],
    deskPositions: [],
  },
  {
    id: 'alc_ai',
    name: 'ALC AI Dept',
    x: 40,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.alc_ai,
    furniture: [
      { type: 'desk', x: 44, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 45, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 44, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 45, y: 10, width: 1, height: 1 },
      { type: 'desk', x: 44, y: 15, width: 3, height: 2 },
      { type: 'monitor', x: 45, y: 15, width: 1, height: 1 },
      { type: 'desk', x: 55, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 56, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 55, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 56, y: 10, width: 1, height: 1 },
      { type: 'desk', x: 55, y: 15, width: 3, height: 2 },
      { type: 'monitor', x: 56, y: 15, width: 1, height: 1 },
      { type: 'plant', x: 42, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 67, y: 2, width: 1, height: 1 },
    ],
    deskPositions: [
      { x: 45, y: 7 },
      { x: 45, y: 12 },
      { x: 45, y: 17 },
      { x: 56, y: 7 },
      { x: 56, y: 12 },
      { x: 56, y: 17 },
    ],
  },
  {
    id: 'arcade_dept',
    name: 'Arcade Dept',
    x: 70,
    y: 0,
    width: 30,
    height: 25,
    type: 'department',
    color: ROOM_COLORS.arcade,
    furniture: [
      { type: 'desk', x: 74, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 75, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 74, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 75, y: 10, width: 1, height: 1 },
      { type: 'desk', x: 85, y: 5, width: 3, height: 2 },
      { type: 'monitor', x: 86, y: 5, width: 1, height: 1 },
      { type: 'desk', x: 85, y: 10, width: 3, height: 2 },
      { type: 'monitor', x: 86, y: 10, width: 1, height: 1 },
      { type: 'plant', x: 72, y: 2, width: 1, height: 1 },
      { type: 'plant', x: 97, y: 2, width: 1, height: 1 },
    ],
    deskPositions: [
      { x: 75, y: 7 },
      { x: 75, y: 12 },
      { x: 86, y: 7 },
      { x: 86, y: 12 },
    ],
  },
  // === Bottom row ===
  {
    id: 'breakroom',
    name: 'Break Room',
    x: 0,
    y: 25,
    width: 25,
    height: 20,
    type: 'breakroom',
    color: ROOM_COLORS.breakroom,
    furniture: [
      { type: 'table', x: 6, y: 30, width: 3, height: 2 },
      { type: 'chair', x: 5, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 7, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 9, y: 32, width: 1, height: 1 },
      { type: 'table', x: 15, y: 30, width: 3, height: 2 },
      { type: 'chair', x: 14, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 16, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 18, y: 32, width: 1, height: 1 },
      { type: 'vending_machine', x: 3, y: 27, width: 1, height: 2 },
      { type: 'couch', x: 10, y: 38, width: 4, height: 2 },
    ],
    deskPositions: [],
  },
  {
    id: 'smoke_area',
    name: 'Smoke Area',
    x: 25,
    y: 25,
    width: 20,
    height: 20,
    type: 'smoke_area',
    color: ROOM_COLORS.smoke_area,
    furniture: [
      { type: 'ashtray', x: 30, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 29, y: 33, width: 1, height: 1 },
      { type: 'chair', x: 31, y: 33, width: 1, height: 1 },
      { type: 'ashtray', x: 37, y: 32, width: 1, height: 1 },
      { type: 'chair', x: 36, y: 33, width: 1, height: 1 },
      { type: 'chair', x: 38, y: 33, width: 1, height: 1 },
      { type: 'plant', x: 27, y: 27, width: 1, height: 1 },
      { type: 'plant', x: 42, y: 27, width: 1, height: 1 },
    ],
    deskPositions: [],
  },
  {
    id: 'bathroom',
    name: 'Bathroom',
    x: 45,
    y: 25,
    width: 15,
    height: 20,
    type: 'bathroom',
    color: ROOM_COLORS.bathroom,
    furniture: [
      { type: 'toilet', x: 48, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 51, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 54, y: 29, width: 1, height: 1 },
      { type: 'toilet', x: 48, y: 35, width: 1, height: 1 },
      { type: 'toilet', x: 51, y: 35, width: 1, height: 1 },
      { type: 'toilet', x: 54, y: 35, width: 1, height: 1 },
    ],
    deskPositions: [],
  },
  {
    id: 'play_area',
    name: 'Play Area',
    x: 60,
    y: 25,
    width: 30,
    height: 20,
    type: 'play_area',
    color: ROOM_COLORS.play_area,
    furniture: [
      { type: 'arcade_machine', x: 64, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 67, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 70, y: 28, width: 1, height: 2 },
      { type: 'arcade_machine', x: 73, y: 28, width: 1, height: 2 },
      { type: 'couch', x: 65, y: 37, width: 4, height: 2 },
      { type: 'couch', x: 75, y: 37, width: 4, height: 2 },
      { type: 'table', x: 80, y: 32, width: 3, height: 2 },
    ],
    deskPositions: [],
  },
]

/** Get doorway positions connecting rooms */
export function getDoorways(): { x: number; y: number; roomA: string; roomB: string }[] {
  return [
    // Planogram -> Hallway
    { x: 30, y: 12, roomA: 'planogram', roomB: 'hallway' },
    // Hallway -> ALC AI
    { x: 40, y: 12, roomA: 'hallway', roomB: 'alc_ai' },
    // ALC AI -> Arcade Dept
    { x: 70, y: 12, roomA: 'alc_ai', roomB: 'arcade_dept' },
    // Hallway -> Break Room (south)
    { x: 20, y: 25, roomA: 'breakroom', roomB: 'hallway' },
    // Hallway -> Smoke Area
    { x: 34, y: 25, roomA: 'hallway', roomB: 'smoke_area' },
    // Smoke Area -> Bathroom
    { x: 45, y: 34, roomA: 'smoke_area', roomB: 'bathroom' },
    // Bathroom -> Play Area
    { x: 60, y: 34, roomA: 'bathroom', roomB: 'play_area' },
    // Hallway to bottom row via main corridor
    { x: 34, y: 25, roomA: 'hallway', roomB: 'breakroom' },
  ]
}
